apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{ values.prod_namespace }}

resources:
  - ../../base
  - route.yaml
  - hpa.yaml
  - pdb.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
