app:
  baseUrl: http://backstage-alb-1076206040.us-east-1.elb.amazonaws.com

backend:
  baseUrl: http://backstage-alb-1076206040.us-east-1.elb.amazonaws.com
  listen: ':7007'
  cors:
    origin: http://backstage-alb-1076206040.us-east-1.elb.amazonaws.com
  csp:
    upgrade-insecure-requests: false
    connect-src: ["'self'", 'http:', 'https:']
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl:
        rejectUnauthorized: false

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: ./templates/nodejs-backend/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/nestjs-backend/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/aws-ecs-infra/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/openshift-deploy/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/argocd-app/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/nodejs-openshift/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/openshift-pipeline-setup/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./catalog/eqt-lab-platform.yaml
      rules:
        - allow: [System, Component]
