{% if values.secret_vars %}
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.artefato_name }}-app-secrets
type: Opaque
stringData:
{% for line in values.secret_vars.split('\n') %}{% if '=' in line %}  ${{ line.split('=')[0] }}: "${{ line.split('=', 1)[1] }}"
{% endif %}{% endfor %}{% endif %}
