apiVersion: v1
kind: Secret
metadata:
  name: git-auth-secret-${{ values.artefato_name }}
  annotations:
    tekton.dev/git-0: https://${{ values.repositorio }}/${{ values.artefato_name }}
type: kubernetes.io/basic-auth
stringData:
  username: ${{ values.artefato_name }}-tkn
  password: ${{ values.git_token }}
