apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-config
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
data:
  NODE_ENV: production
  PORT: "${{ values.port }}"
  APP_NAME: ${{ values.name }}
