apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
spec:
  lookupPolicy:
    local: true
