apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: lucasreis-tests/${{ values.name }}-gitops
    argocd/app-name: ${{ values.name }}-dev,${{ values.name }}-prod
    backstage.io/kubernetes-label-selector: app=${{ values.name }}
  tags:
    - argocd
    - gitops
    - kustomize
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
