apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: image-registry.openshift-image-registry.svc:5000/${{ values.dev_namespace }}/${{ values.name }}:latest
          ports:
            - containerPort: ${{ values.port }}
          envFrom:
            - configMapRef:
                name: ${{ values.name }}-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: ${{ values.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: ${{ values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
